server:
  port: 8080

spring:
  application:
    name: bc-ck-web
  http:
    encoding: { charset: UTF-8, enable: true, force: true }
  redis:
    host: redis.dreamtale.com
    port: 6379
  datasource:
    username: dev001
    password: Dev.qwe123
    name: dreamtale_user
    url: jdbc:mysql://mysql.dreamtale.com:3306/dreamtale_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  #z增加thymeleaf的支持
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-5
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dreamtale.ck.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

